# Generated by Django 3.1.2 on 2020-12-09 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50)),
                ('author_birth', models.DateField(default='2020-12-09')),
                ('author_dead_time', models.DateField(default='2020-12-09')),
                ('author_major_exp', models.TextField(default='')),
                ('author_bei_zhu', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultMusic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_name', models.CharField(max_length=50, unique=True)),
                ('music_ge_chi', models.TextField()),
                ('music_bei_zhu', models.TextField(default='')),
                ('bo_fang_liang', models.IntegerField(default=0)),
                ('music_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default_music.author')),
            ],
        ),
        migrations.CreateModel(
            name='Repeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeat_name', models.CharField(max_length=10)),
                ('repeat_article', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_title', models.CharField(max_length=20)),
                ('suggestion_article', models.TextField()),
                ('suggestion_author', models.CharField(max_length=20)),
                ('suggestion_time', models.DateTimeField()),
                ('suggestion_repeat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default_music.repeat')),
            ],
        ),
        migrations.CreateModel(
            name='Ge_dan_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ge_dan_name', models.CharField(max_length=20)),
                ('number', models.IntegerField(default=0)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default_music.defaultmusic')),
            ],
        ),
    ]
