# Generated by Django 3.1.2 on 2020-12-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_music', '0002_auto_20201210_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_birth',
            field=models.DateField(default='2020-12-12'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_dead_time',
            field=models.DateField(default='2020-12-12'),
        ),
    ]
