# Generated by Django 3.1.2 on 2020-12-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_music', '0003_auto_20201212_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_birth',
            field=models.DateField(default='2020-12-14'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_dead_time',
            field=models.DateField(default='2020-12-14'),
        ),
    ]
