# Generated by Django 3.1.2 on 2020-12-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geming', models.CharField(max_length=20, unique=True)),
                ('gechi', models.TextField()),
                ('author', models.CharField(max_length=10)),
                ('beizhu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Music_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=20, unique=True)),
                ('numbers', models.IntegerField()),
                ('bo_fang_liang', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('last_login_in', models.DateField()),
                ('img', models.ImageField(default='', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('sex', models.CharField(max_length=2)),
                ('birthday', models.CharField(max_length=20)),
                ('email', models.EmailField(default='00000@qq.com', max_length=254)),
                ('ai_hao', models.TextField()),
            ],
        ),
    ]
