# Generated by Django 3.1.2 on 2020-12-09 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='my_music.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='userInfo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='my_music.userinfo'),
        ),
    ]
