# Generated by Django 3.1.2 on 2020-12-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_music', '0002_auto_20201209_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(max_length=4),
        ),
    ]
