# Generated by Django 3.1.2 on 2020-12-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_music', '0003_auto_20201210_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='beizhu',
            field=models.TextField(default=''),
        ),
    ]
